name: Deploy Docker Image

on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:
    inputs:
      no-cache:
        description: Build Docker image without using cache
        required: false
        default: false
        type: boolean

jobs:
  publish:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    uses: hyuabot-developers/hyuabot-infrastructure/.github/workflows/publish-immutable-image.yml@e26660725b546d1de4021f5ac95f1be6c4c17c35
    with:
      image-repository: localhost:5000/hyuabot-building-updater
      no-cache: ${{ github.event_name == 'workflow_dispatch' && inputs['no-cache'] }}
    secrets:
      RUNNER_ADMIN_TOKEN: ${{ secrets.RUNNER_ADMIN_TOKEN }}
      FIRST_HOST: ${{ secrets.SSH_HOST || secrets.ORACLE_TRANSFER_TARGET }}
